### ISSUE TITLE
clang-tidy reports a possible null pointer deference since 97a9214

### ISSUE THREAD

**Issue by fischerling** [axboe/liburing#546]
The handling of the legacy `LIBURING_UDATA_TIMEOUT` in `__io_uring_peek_cqe`
may cause `io_uring_wait_cqe` to return without an error but with the passed cqe pointer filled with `NULL`.

If this is valid behavior we should at least mentioned it in the `io_uring_wait_cqe.3` man page.

It is likely introduced with 97a9214 because __io_uring_peek_cqe is now used in io_uring_wait_cqe and reverting it make clang-tidy happy :)

### Used software versions:

* liburing: current master (7fed734f70fc3b18e504f75ed52b77192729c874)
* clang-tidy: LLVM version 13.0.1

### Used dummy program:

```c
#include <stdio.h>
#include <liburing.h>

const unsigned IORING_ENTRIES = 2;

int main() {
	struct io_uring ring;
	struct io_uring_cqe* cqe;
	io_uring_queue_init(IORING_ENTRIES, &ring, 0);
	io_uring_wait_cqe(&ring, &cqe);
	printf("%d\n", cqe->res);
	return 0;
}
```

### Clang-tidy report:

```
main.c:11:17: error: Access to field 'res' results in a dereference of a null pointer (loaded from variable 'cqe') [clang-analyzer-core.NullDereference,-warnings-as-errors]
        printf("%d\n", cqe->res);
                       ^~~
main.c:10:2: note: Calling 'io_uring_wait_cqe'
        io_uring_wait_cqe(&ring, &cqe);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
subprojects/liburing/src/include/liburing.h:878:6: note: Calling '__io_uring_peek_cqe'
        if (__io_uring_peek_cqe(ring, cqe_ptr, NULL))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
subprojects/liburing/src/include/liburing.h:835:7: note: Assuming 'available' is not equal to 0, which participates in a condition later
                if (!available)
                    ^~~~~~~~~~
subprojects/liburing/src/include/liburing.h:835:3: note: Taking false branch
                if (!available)
                ^
subprojects/liburing/src/include/liburing.h:839:7: note: Assuming the condition is true
                if (!(ring->features & IORING_FEAT_EXT_ARG) &&
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
subprojects/liburing/src/include/liburing.h:839:7: note: Left side of '&&' is true
subprojects/liburing/src/include/liburing.h:840:5: note: Assuming the condition is true
                                cqe->user_data == LIBURING_UDATA_TIMEOUT) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
subprojects/liburing/src/include/liburing.h:839:3: note: Taking true branch
                if (!(ring->features & IORING_FEAT_EXT_ARG) &&
                ^
subprojects/liburing/src/include/liburing.h:841:8: note: Assuming field 'res' is < 0, which participates in a condition later
                        if (cqe->res < 0)
                            ^~~~~~~~~~~~
subprojects/liburing/src/include/liburing.h:841:4: note: Taking true branch
                        if (cqe->res < 0)
                        ^
subprojects/liburing/src/include/liburing.h:844:9: note: 'err' is not equal to 0, which participates in a condition later
                        if (!err)
                             ^~~
subprojects/liburing/src/include/liburing.h:844:4: note: Taking false branch
                        if (!err)
                        ^
subprojects/liburing/src/include/liburing.h:846:4: note: Null pointer value stored to 'cqe'
                        cqe = NULL;
                        ^~~~~~~~~~
subprojects/liburing/src/include/liburing.h:849:3: note:  Execution continues on line 852
                break;
                ^
subprojects/liburing/src/include/liburing.h:852:2: note: Null pointer value stored to 'cqe'
        *cqe_ptr = cqe;
        ^~~~~~~~~~~~~~
subprojects/liburing/src/include/liburing.h:853:6: note: 'nr_available' is null
        if (nr_available)
            ^~~~~~~~~~~~
subprojects/liburing/src/include/liburing.h:853:2: note: Taking false branch
        if (nr_available)
        ^
subprojects/liburing/src/include/liburing.h:878:6: note: Returning from '__io_uring_peek_cqe'
        if (__io_uring_peek_cqe(ring, cqe_ptr, NULL))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
subprojects/liburing/src/include/liburing.h:878:2: note: Taking true branch
        if (__io_uring_peek_cqe(ring, cqe_ptr, NULL))
        ^
main.c:10:2: note: Returning from 'io_uring_wait_cqe'
        io_uring_wait_cqe(&ring, &cqe);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c:11:17: note: Access to field 'res' results in a dereference of a null pointer (loaded from variable 'cqe')
        printf("%d\n", cqe->res);
                       ^~~
```

**Comment by axboe** [comment]
That looks legit, and I actually think there's another bug in that commit... Testing a fix now, thanks for the report!

**Comment by axboe** [comment]
Pushed a fix, can you check?

**Comment by fischerling** [comment]
Yes fixed by 2eda3594c0056079fa3e3b9fba52e72ed4ff6183.
Glad I could help.
