### ISSUE TITLE
liburing-2.3 build failure on musl (uses non-portable `error.h`)

### ISSUE THREAD

**Issue by thesamesam** [axboe/liburing#786]
Hi folks,

We had a report downstream (https://bugs.gentoo.org/888956) in Gentoo of liburing-2.3 failing to build on musl.

Within the examples/ and tests/ dirs, various programs use `<error.h>` which isn't portable. Is it possible to make the use of this conditional? Thanks.

```
x86_64-gentoo-linux-musl-gcc -D_GNU_SOURCE -D__SANE_USERSPACE_TYPES__ -I../src/include/ -include ../config-host.h -pipe -march=native -fno-diagnostics-color -O2 -Wno-unused-parameter -Wno-sign-compare -Wstringop-overflow=0 -Warray-bounds=0 -DLIBURING_BUILD_TEST -o single-issuer.t single-issuer.c helpers.o -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -L../src/ -luring -lpthread
single-issuer.c:8:10: fatal error: error.h: No such file or directory
    8 | #include <error.h>
      |          ^~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:214: single-issuer.t] Error 1 shuffle=537543450
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/var/tmp/portage/sys-libs/liburing-2.3/work/liburing-2.3-abi_x86_64.amd64/test'
make: *** [Makefile:11: all] Error 2 shuffle=537543450
 * ERROR: sys-libs/liburing-2.3::gentoo failed (compile phase):
 *   emake failed
``

**Comment by ammarfaizi2** [comment]
Looking at the manpage

```
NAME
       error, error_at_line, error_message_count, error_one_per_line, error_print_progname - glibc error reporting functions

SYNOPSIS
       #include <error.h>

       void error(int status, int errnum, const char *format, ...);

       void error_at_line(int status, int errnum, const char *filename,
                          unsigned int linenum, const char *format, ...);

       extern unsigned int error_message_count;

       extern int error_one_per_line;

       extern void (*error_print_progname) (void);

...
...
...

CONFORMING TO
       These functions and variables are GNU extensions, and should not be used in programs intended to be portable.
```

These functions are just for error printing purpose; we can replace
them with `fprintf(stderr, ...)` + `exit(T_EXIT_FAIL)`, it should be easy.

I will send a patch. Thanks for reporting,

**Comment by CobaltCause** [comment]
Looks like this regressed in 3360787511c7cdb7fcc5737baae072ce8e8c11b9 which made it into the release of version 2.7

**Comment by CobaltCause** [comment]
Oh and it looks like this was already fixed by ff0bc26d3220f9b7782e17ca7a93388a08f6b1dd but hasn't appeared in a release yet

**Comment by axboe** [comment]
Would be great if we could add a musl build to the CI list...
